version: 2
jobs:
    javascript:
      working_directory: "~/ci-build"
      docker:
        - image: "circleci/node:10.5.0"
      steps:
        - run:
            name: "Setup NPMRC"
            command: "echo $NPMRC > ~/.npmrc"
        - checkout
        - run:
            name: "NPM: Install dependencies"
            command: "cd javascript && npm ci"
        - run: cd javascript && npm run lint
        - run: cd javascript && npm run flow
        - run: cd javascript && npm run test
workflows:
  version: 2
  build_and_test:
    jobs:
      - javascript